apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-static-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: dremmeng/my-static-website:latest
        ports:
        - containerPort: 80
      nodeSelector:
        node-role.kubernetes.io/master2: master2
        node-role.kubernetes.io/worker: worker
