apiVersion: v1
kind: Service
metadata:
  name: static-website-service
spec:
  type: NodePort
  selector:
    app: static-website
  ports:
    - protocol: TCP
      port: 80        # Service port (internally)
      targetPort: 80  # Container port
      nodePort: 30000 # NodePort (optional)