apiVersion: v1
kind: Service
metadata:
  name: my-static-website
spec:
  selector:
    app: website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
