apiVersion: v1
kind: Service
metadata:
  name: my-web-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: my-web-app  # Should match the labels in your deployment
  ports:
    - protocol: TCP
      port: 80          # Port the service will be exposed on within the cluster
      targetPort: 80    # Port on the container to forward traffic to
      nodePort: 30080   # NodePort for external access (within the range 30000-32767)
